# Домашнее задание 2

В данном домашнем задании вы еще раз потренируетесь в применении библиотек numpy и pandas.
Задание состоит из 3 этапов:
- Тренировка с numpy
- Тренировака с pandas
- Дополнительное задание с геоданными

In [1]:
import pandas as pd
import numpy as np

## Numpy

#### 1. Дано несколько numpy-массивов одной длины. Найдите максимальное значение для каждого индекса (максимум среди всех значений в массивах с индексом 0 и т.д.).
Авторское решение умещается в 3 строки.\
**Пример**\
Дано: [1, 2, 3], [1, 1, 1], [2, 2, 2]\
Ответ: [2, 2, 3]

In [2]:
def task1(list_of_arrays):
    # TODO
    pass

task1([np.array([1, 2, 3]), np.array([1, 1, 1]), np.array([2, 2, 2])]) == np.array([2, 2, 3])

array([False, False, False])

#### 2. Найти в матрице самый близкий элемент к заданному.
Авторское решение умещается в 1 строку.\
**Пример**\
Матрица:\
1 2 3 4 5\
6 7 8 9 9\
Число: 3.3\
Наиболее близкое число 3.  
Число: -0.5  
Наиболее близкое число 1.

In [3]:
def task2(matrix, number):
    # TODO
    pass

task2(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9]).reshape(2, 5), 3.3) == 3

False

#### 3. Создайте квадратную матрицу размера NxN следующего вида.
Авторское решение умещается в 1 строку.\
**Пример**\
0 1 2 3\
1 2 3 4\
2 3 4 5\
3 4 5 6

In [4]:
def task3(size):
    # TODO
    pass

task3(2) == np.array([[0, 1], [1, 2]])

array([[False, False],
       [False, False]])

#### 4. Сделайте полный разворот матрицы.
Авторское решение умещается в 1 строку.\
**Пример**\
На вход подается матрица:\
1 2 3\
4 5 6\
7 8 9

А функция возвращает:\
9 8 7\
6 5 4\
3 2 1

In [5]:
def task4(a):
    # TODO
    pass

matrix = np.arange(2 * 1).reshape(2, 1)
task4(matrix) == np.array([[1], [0]])

array([[False],
       [False]])

## Pandas

Данные содержат вызовы службы 311, которая отвечает за неэкстренные службы. Более подробно про службу 311 можно почитать на википедии: https://en.wikipedia.org/wiki/3-1-1 \
Ниже дано описание 6 колонок, которые вам понадобятся при выполнении этого задания. \
Данные представлены в обрезанном виде, чтобы не было проблем при работе с ними. Полный датасет можно найти, например, тут: https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9

`Agency` \
Acronym of responding City Government Agency

`City` \
City of the incident location provided by geovalidation.

`Complaint Type` \
This is the first level of a hierarchy identifying the topic of the incident or condition. Complaint Type may have a corresponding Descriptor (below) or may stand alone.

`Created Date` \
Date SR (Service Request) was created.

`Descriptor` \
This is  associated to the Complaint Type, and provides further detail on the incident or condition. Descriptor values are dependent on the Complaint Type, and are not always required in SR.

`Location Type` \
Describes the type of location used in the address information

In [ ]:
filepath = 'https://raw.githubusercontent.com/jvns/pandas-cookbook/master/data/311-service-requests.csv'
cols = ['Agency', 'City', 'Complaint Type', 'Created Date', 'Descriptor', 'Location Type']
df = pd.read_csv(filepath, usecols=cols, low_memory=False)

In [ ]:
df.head()

#### 1. Какое agency встречается больше 30_000 раз?

In [ ]:
# Ваш код здесь

#### 2. Какое количество раз встречается `Complaint Type == Noise` при условии `agency == DEP`?

In [ ]:
# Ваш код здесь

#### 3. Найдите дату подачи самой поздней закрытой жалобы.

In [ ]:
# Ваш код здесь

#### 4. Для самой поздней закрытой жалобы определите `City` и  `Descriptor`.

In [ ]:
# Ваш код здесь

#### 5. На сколько больше жалоб на громкие разговоры, чем на громкую музыку?
Жалобы только этих 2 типов попадают под `Compaint Type == Noise - Street/Sidewalk`.

In [ ]:
# Ваш код здесь

#### 6. Найдите самую частую локацию в Нью-Йорке, где происходит больше всего нарушений (в сумме) по следующим типам:
- Derelict Vehicle
- Urinating in Public (LOL)
- Drinking

Город надо определять по полю `City`. Типы нарушений описаны в колонке `Complaint Type`. Локацию внутри города можно определить по колонке `Location Type`.

In [ ]:
# Ваш код здесь

## Дополнительное задание

**Внимание!** Данное задание требует изучения дополнительных материалов, которые мы не проходили в курсе.

1. Сделайте случайное выборку из 30 строк. 
2. Найдите координаты этих точек на карте (поля `Incident Address` и `City`). Прочитать подробнее про геокоддеры можно, например, тут https://towardsdatascience.com/geocode-with-python-161ec1e62b89
3. Найдите 5 наиболее похожих между собой точек (любым способом).
4. Найдите среднюю координату на основе этих 5 точек.
5. Отобразите на карте все 30 точек (или меньше, если геокодер не нашел все адреса) с центром в точке из пункта 4.

In [ ]:
from geopy.extra.rate_limiter import RateLimiter
from scipy.spatial.distance import cdist
from geopy.geocoders import Nominatim
import folium

In [ ]:
filepath = 'https://raw.githubusercontent.com/jvns/pandas-cookbook/master/data/311-service-requests.csv'
cols = ['City', 'Incident Address']
df = pd.read_csv(filepath, usecols=cols, low_memory=False)

In [ ]:
# Ваш код здесь